plugins {
  id 'java'
  id 'com.vanniktech.maven.publish' version('0.37.0')
}

repositories {
  mavenCentral()
}

dependencies {
	api "com.badlogicgames.gdx:gdx:$gdxVersion"

	testImplementation 'org.junit.jupiter:junit-jupiter:5.10.2'
	testImplementation 'org.mockito:mockito-core:4.11.0'
	testImplementation 'org.mockito:mockito-inline:4.11.0'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
	useJUnitPlatform()
	systemProperty 'net.bytebuddy.experimental', 'true'
}

mavenPublishing {
  coordinates(group.toString(), 'gdx-relativeui', version.toString())

  pom {
    name = "gdx-relativeui"
    description = "RelativeLayout for LibGDX Scene2d."
    inceptionYear = "2026"
    url = "https://github.com/iktools/gdx-relativeui"
    licenses {
      license {
        name = "Apache License, Version 2.0"
        url = "https://www.apache.org/licenses/LICENSE-2.0"
        distribution = "https://www.apache.org/licenses/LICENSE-2.0"
      }
    }
    developers {
      developer {
        id = "iktools"
        name = "IK Tools"
        url = "https://github.com/iktools/"
      }
    }
    scm {
      url = "https://github.com/iktools/gdx-relativeui"
      connection = "scm:git:git://github.com/iktools/gdx-relativeui.git"
      developerConnection = "scm:git:ssh://git@github.com/iktools/gdx-relativeui.git"
    }
  }
}
